--- #YAML:1.0
name:                CPAN::Testers::WWW::Statistics
version:             0.87
abstract:            Scripts to create the CPAN Testers Statistics website
author:
  - Barbie <barbie@cpan.org>

license:             artistic_2
distribution_type:   module
installdirs:         site

requires:
  CGI:                              0
  Class::Accessor::Fast:            0
  Config::IniFiles:                 0
  CPAN::Testers::Common::DBUtils:   0.03
  DBI:                              0
  DBD::mysql:                       0
  DBD::SQLite:                      0
  GD::Graph::lines:                 0
  Email::Simple:                    0
  File::Basename:                   0
  File::Copy:                       0
  File::Path:                       0
  File::Slurp:                      0
  Getopt::ArgvFile:                 0
  Getopt::Long:                     0
  HTML::Entities:                   0
  HTTP::Request:                    0
  IO::File:                         0
  JSON:                             0
  LWP::UserAgent:                   0
  Sort::Versions:                   0
  Template:                         0
  Time::Piece:                      0
recommends:
  Test::CPAN::Meta:                 0.13
  Test::JSON::Meta:                 0.08
  Test::More:                       0.70
  Test::MockObject:                 0
  Test::Pod:                        1.00
  Test::Pod::Coverage:              0.08
build_requires:
  Archive::Extract:                 0
  Archive::Zip:                     0
  File::Spec:                       0
  Test::Differences:                0
  Test::More:                       0.70

provides:
  CPAN::Testers::WWW::Statistics:
    file:     lib/CPAN/Testers/WWW/Statistics.pm
    version:  0.87
  CPAN::Testers::WWW::Statistics::Graphs:
    file:     lib/CPAN/Testers/WWW/Statistics/Graphs.pm
    version:  0.87
  CPAN::Testers::WWW::Statistics::Pages:
    file:     lib/CPAN/Testers/WWW/Statistics/Pages.pm
    version:  0.87

resources:
  repository: http://github.com/barbie/cpan-testers-www-statistics

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
