--- #YAML:1.0
name:                CPAN::Testers::WWW::Statistics
version:             0.64
abstract:            Scripts to create the cpanstats website
author:
  - Barbie <barbie@cpan.org>

license:             perl
distribution_type:   module
installdirs:         site

requires:
  CGI:                              0
  Class::Accessor::Chained::Fast:   0
  Config::IniFiles:                 0
  CPAN::Testers::Common::DBUtils:   0.03
  DBD::mysql:                       0
  DBD::SQLite:                      0
  GD::Graph::lines:                 0
  Email::Simple:                    0
  File::Basename:                   0
  File::Copy:                       0
  File::Path:                       0
  Getopt::ArgvFile:                 0
  Getopt::Long:                     0
  HTML::Entities:                   0
  IO::File:                         0
  Sort::Versions:                   0
  Template:                         0
  Time::Piece:                      0
  WWW::Mechanize:                   0
recommends:
  Test::More:                       0.70
  Test::MockObject:                 0
  Test::Pod:                        1.00
  Test::Pod::Coverage:              0.08
  Test::CPAN::Meta:                 0.12
build_requires:
  Test::More:                       0.01
  Test::Differences:                0
  Archive::Zip:                     0
  Archive::Extract:                 0
  File::Slurp:                      0
  File::Spec:                       0

provides:
  CPAN::Testers::WWW::Statistics:
    file:     lib/CPAN/Testers/WWW/Statistics.pm
    version:  0.64
  CPAN::Testers::WWW::Statistics::Graphs:
    file:     lib/CPAN/Testers/WWW/Statistics/Graphs.pm
    version:  0.64
  CPAN::Testers::WWW::Statistics::Pages:
    file:     lib/CPAN/Testers/WWW/Statistics/Pages.pm
    version:  0.64

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
